// Client access to the research-packet return/verification/follow-up/artifact
// tables (Phases 2-7 of docs/research-workflow/). Same posture as
// src/lib/packets.ts: all reads and writes go through owner-scoped RLS;
// controller rows (recognized_blocks, final_artifacts, return status
// verdicts) are written by Edge Functions with the service role.
//
// The generated Supabase types are regenerated by Lovable tooling and don't
// include these tables yet, so this module is the single place that casts
// around them. Once types regenerate, delete the casts here and nothing
// else moves.

import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type PacketReturn = {
  id: string;
  packet_id: string;
  piece_id: string;
  user_id: string;
  method: "photos" | "dictation" | "mixed";
  status: "collecting" | "recognizing" | "needs_review" | "verified" | "failed";
  error: string | null;
  created_at: string;
  updated_at: string;
};

export type PageImage = {
  id: string;
  return_id: string;
  user_id: string;
  storage_path: string;
  page_number: number | null;
  position: number;
  quality: { ok: boolean; issues: Array<{ code: string; message: string }> } | null;
  status: "uploaded" | "recognized" | "rejected" | "failed";
  created_at: string;
  updated_at: string;
};

export type RecognizedBlock = {
  id: string;
  page_image_id: string;
  return_id: string;
  user_id: string;
  attempt: number;
  position: number;
  kind: "response" | "annotation" | "followup" | "note";
  location: Record<string, unknown> | null;
  text: string;
  confidence: number | null;
  annotation_type: string | null;
  linked_question_id: string | null;
  linked_anchor: string | null;
  created_at: string;
};

export type DictationSegment = {
  id: string;
  return_id: string;
  user_id: string;
  position: number;
  transcript: string;
  audio_path: string | null;
  resolved_target: {
    page?: number;
    question?: string;
    anchor?: string;
    followup?: number;
  } | null;
  linked_question_id: string | null;
  status: "draft" | "approved";
  created_at: string;
  updated_at: string;
};

export type VerificationCorrection = {
  id: string;
  return_id: string;
  user_id: string;
  block_id: string | null;
  segment_id: string | null;
  action: "confirm" | "correct" | "reject";
  corrected_text: string | null;
  corrected_meaning: string | null;
  linked_question_id: string | null;
  created_at: string;
};

export type FollowupQuestion = {
  id: string;
  packet_id: string;
  piece_id: string;
  user_id: string;
  position: number;
  student_text: string;
  suggested_text: string | null;
  refinement_reason: string | null;
  approved_text: string | null;
  source: "handwriting" | "dictation" | "typed" | "suggested";
  status: "submitted" | "refined" | "approved" | "researched";
  created_at: string;
  updated_at: string;
};

export type FinalArtifact = {
  id: string;
  piece_id: string;
  packet_id: string | null;
  run_id: string | null;
  user_id: string;
  kind: "docx" | "pptx";
  status: "generating" | "ready" | "failed";
  storage_path: string | null;
  title: string | null;
  provenance: Record<string, unknown> | null;
  error: string | null;
  created_at: string;
  updated_at: string;
};

export type PacketPiece = {
  id: string;
  user_id: string;
  slug: string;
  workflow: "longform" | "research_packet";
  stage: string;
  created_at: string;
};

// Untyped view of the client until the generated types include these tables
// (see the module comment).
const db = supabase as unknown as SupabaseClient;

async function currentUserId(): Promise<string> {
  const { data, error } = await supabase.auth.getUser();
  if (error || !data.user) throw new Error("Not signed in");
  return data.user.id;
}

// ---------------------------------------------------------------------------
// Piece-scoped reads for the project hub.

export async function getPiece(pieceId: string): Promise<PacketPiece | null> {
  const { data, error } = await db
    .from("pieces")
    .select("id, user_id, slug, workflow, stage, created_at")
    .eq("id", pieceId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return (data as PacketPiece) ?? null;
}

export async function listPacketsByPiece(pieceId: string) {
  const { data, error } = await db
    .from("packets")
    .select("*")
    .eq("piece_id", pieceId)
    .order("version", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as Array<{
    id: string;
    piece_id: string;
    run_id: string;
    user_id: string;
    version: number;
    supersedes_packet_id: string | null;
    status: "generated" | "reviewed";
    analysis: Record<string, unknown> | null;
    created_at: string;
  }>;
}

export async function listRunsByPiece(pieceId: string) {
  const { data, error } = await db
    .from("agent_runs")
    .select("id, kind, status, error, created_at, completed_at")
    .eq("piece_id", pieceId)
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as Array<{
    id: string;
    kind: string;
    status: string;
    error: string | null;
    created_at: string;
    completed_at: string | null;
  }>;
}

export async function listReturnsByPiece(pieceId: string): Promise<PacketReturn[]> {
  const { data, error } = await db
    .from("packet_returns")
    .select("*")
    .eq("piece_id", pieceId)
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as PacketReturn[];
}

export async function listFollowupsByPiece(pieceId: string): Promise<FollowupQuestion[]> {
  const { data, error } = await db
    .from("followup_questions")
    .select("*")
    .eq("piece_id", pieceId)
    .order("position", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as FollowupQuestion[];
}

export async function listArtifactsByPiece(pieceId: string): Promise<FinalArtifact[]> {
  const { data, error } = await db
    .from("final_artifacts")
    .select("*")
    .eq("piece_id", pieceId)
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as FinalArtifact[];
}

// ---------------------------------------------------------------------------
// Returns: create + collect.

export async function createPacketReturn(input: {
  packetId: string;
  pieceId: string;
  method: PacketReturn["method"];
}): Promise<PacketReturn> {
  const userId = await currentUserId();
  const { data, error } = await db
    .from("packet_returns")
    .insert({
      packet_id: input.packetId,
      piece_id: input.pieceId,
      user_id: userId,
      method: input.method,
      status: "collecting",
    })
    .select("*")
    .single();
  if (error) throw new Error(error.message);
  return data as PacketReturn;
}

export async function getReturn(returnId: string): Promise<PacketReturn | null> {
  const { data, error } = await db
    .from("packet_returns")
    .select("*")
    .eq("id", returnId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return (data as PacketReturn) ?? null;
}

export async function updateReturnMethod(
  returnId: string,
  method: PacketReturn["method"],
): Promise<void> {
  const { error } = await db
    .from("packet_returns")
    .update({ method, updated_at: new Date().toISOString() })
    .eq("id", returnId);
  if (error) throw new Error(error.message);
}

/** Owner approval: the verified response set becomes authoritative. */
export async function markReturnVerified(returnId: string): Promise<void> {
  const { error } = await db
    .from("packet_returns")
    .update({ status: "verified", updated_at: new Date().toISOString() })
    .eq("id", returnId);
  if (error) throw new Error(error.message);
}

// ---------------------------------------------------------------------------
// Page images.

export async function registerPageImage(input: {
  returnId: string;
  storagePath: string;
  position: number;
  pageNumber?: number | null;
}): Promise<PageImage> {
  const userId = await currentUserId();
  const { data, error } = await db
    .from("page_images")
    .insert({
      return_id: input.returnId,
      user_id: userId,
      storage_path: input.storagePath,
      position: input.position,
      page_number: input.pageNumber ?? null,
      status: "uploaded",
    })
    .select("*")
    .single();
  if (error) throw new Error(error.message);
  return data as PageImage;
}

export async function listPageImages(returnId: string): Promise<PageImage[]> {
  const { data, error } = await db
    .from("page_images")
    .select("*")
    .eq("return_id", returnId)
    .order("position", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as PageImage[];
}

export async function updatePageImage(
  id: string,
  patch: Partial<Pick<PageImage, "page_number" | "position">>,
): Promise<void> {
  const { error } = await db
    .from("page_images")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function deletePageImage(image: PageImage): Promise<void> {
  const { error } = await db.from("page_images").delete().eq("id", image.id);
  if (error) throw new Error(error.message);
  // Best-effort: remove the underlying object too (RLS folder-scoped).
  await supabase.storage.from("packet-returns").remove([image.storage_path]);
}

// ---------------------------------------------------------------------------
// Recognized blocks + dictation + corrections (review surface).

export async function listRecognizedBlocks(returnId: string): Promise<RecognizedBlock[]> {
  const { data, error } = await db
    .from("recognized_blocks")
    .select("*")
    .eq("return_id", returnId)
    .order("position", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as RecognizedBlock[];
}

export async function addDictationSegment(input: {
  returnId: string;
  transcript: string;
  position: number;
  resolvedTarget?: DictationSegment["resolved_target"];
  linkedQuestionId?: string | null;
  audioPath?: string | null;
}): Promise<DictationSegment> {
  const userId = await currentUserId();
  const { data, error } = await db
    .from("dictation_segments")
    .insert({
      return_id: input.returnId,
      user_id: userId,
      transcript: input.transcript,
      position: input.position,
      resolved_target: input.resolvedTarget ?? null,
      linked_question_id: input.linkedQuestionId ?? null,
      audio_path: input.audioPath ?? null,
      status: "draft",
    })
    .select("*")
    .single();
  if (error) throw new Error(error.message);
  return data as DictationSegment;
}

export async function listDictationSegments(returnId: string): Promise<DictationSegment[]> {
  const { data, error } = await db
    .from("dictation_segments")
    .select("*")
    .eq("return_id", returnId)
    .order("position", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as DictationSegment[];
}

export async function updateDictationSegment(
  id: string,
  patch: Partial<
    Pick<
      DictationSegment,
      "transcript" | "resolved_target" | "linked_question_id" | "status" | "position"
    >
  >,
): Promise<void> {
  const { error } = await db
    .from("dictation_segments")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function deleteDictationSegment(id: string): Promise<void> {
  const { error } = await db.from("dictation_segments").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

export async function addCorrection(input: {
  returnId: string;
  blockId?: string | null;
  segmentId?: string | null;
  action: VerificationCorrection["action"];
  correctedText?: string | null;
  correctedMeaning?: string | null;
  linkedQuestionId?: string | null;
}): Promise<void> {
  const userId = await currentUserId();
  const { error } = await db.from("verification_corrections").insert({
    return_id: input.returnId,
    user_id: userId,
    block_id: input.blockId ?? null,
    segment_id: input.segmentId ?? null,
    action: input.action,
    corrected_text: input.correctedText ?? null,
    corrected_meaning: input.correctedMeaning ?? null,
    linked_question_id: input.linkedQuestionId ?? null,
  });
  if (error) throw new Error(error.message);
}

export async function listCorrections(returnId: string): Promise<VerificationCorrection[]> {
  const { data, error } = await db
    .from("verification_corrections")
    .select("*")
    .eq("return_id", returnId)
    .order("created_at", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as VerificationCorrection[];
}

// ---------------------------------------------------------------------------
// Follow-up questions.

export async function addFollowupQuestion(input: {
  packetId: string;
  pieceId: string;
  position: number;
  studentText: string;
  source: FollowupQuestion["source"];
}): Promise<FollowupQuestion> {
  const userId = await currentUserId();
  const { data, error } = await db
    .from("followup_questions")
    .insert({
      packet_id: input.packetId,
      piece_id: input.pieceId,
      user_id: userId,
      position: input.position,
      student_text: input.studentText,
      source: input.source,
      status: "submitted",
    })
    .select("*")
    .single();
  if (error) throw new Error(error.message);
  return data as FollowupQuestion;
}

export async function updateFollowupQuestion(
  id: string,
  patch: Partial<Pick<FollowupQuestion, "student_text" | "approved_text" | "status" | "position">>,
): Promise<void> {
  const { error } = await db
    .from("followup_questions")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function deleteFollowupQuestion(id: string): Promise<void> {
  const { error } = await db.from("followup_questions").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

// ---------------------------------------------------------------------------
// Artifact downloads (free — no credits attach to downloads).

export async function artifactDownloadUrl(artifact: FinalArtifact): Promise<string> {
  if (!artifact.storage_path) throw new Error("Artifact has no file yet");
  const { data, error } = await supabase.storage
    .from("final-artifacts")
    .createSignedUrl(artifact.storage_path, 60 * 10);
  if (error || !data?.signedUrl) throw new Error(error?.message ?? "Could not sign URL");
  return data.signedUrl;
}
