// Client access to the research-packet tables (Phase 1 of
// docs/research-workflow/). All reads and writes go through RLS
// (owner-scoped); packet rows are created only by Edge Functions at
// fetch-back, and the only client-writable packet column is `status`
// (generated → reviewed) via a column-scoped grant.
//
// The generated Supabase types (src/integrations/supabase/types.ts) don't
// include these tables yet — they are regenerated by Lovable tooling, never
// hand-edited — so this module is the single place that casts around them.
// Once types regenerate, delete the casts here and nothing else moves.

import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export const QUESTION_FUNCTIONS = [
  "prior_belief",
  "stakes",
  "evidence_integrity",
  "missing_perspective",
  "ground_truth",
  "expert_interrogation",
  "counterargument",
  "definition_framing",
  "action",
  "followup",
] as const;
export type QuestionFunction = (typeof QUESTION_FUNCTIONS)[number];

export const RESPONSE_SPACES = ["lines_3", "lines_5", "third_page", "half_page", "box"] as const;
export type ResponseSpace = (typeof RESPONSE_SPACES)[number];

export type Packet = {
  id: string;
  piece_id: string;
  run_id: string;
  user_id: string;
  version: number;
  status: "generated" | "reviewed";
  analysis: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
};

export type PacketQuestion = {
  id: string;
  packet_id: string;
  user_id: string;
  position: number;
  function: QuestionFunction;
  claim_ref: string;
  prompt: string;
  guidance: string | null;
  response_space: ResponseSpace;
  locked: boolean;
  source: "generated" | "user";
  edited: boolean;
};

/** Human labels for the question functions, used by the review screen. */
export const FUNCTION_LABELS: Record<QuestionFunction, string> = {
  prior_belief: "Prior belief",
  stakes: "Stakes",
  evidence_integrity: "Evidence integrity",
  missing_perspective: "Missing perspective",
  ground_truth: "Ground-truthing",
  expert_interrogation: "Expert interrogation",
  counterargument: "Counterargument",
  definition_framing: "Definition & framing",
  action: "Action",
  followup: "Follow-up research",
};

export const RESPONSE_SPACE_LABELS: Record<ResponseSpace, string> = {
  lines_3: "3 lines",
  lines_5: "5 lines",
  third_page: "Third of a page",
  half_page: "Half page",
  box: "Open box",
};

// Untyped view of the client until the generated types include the packet
// tables (see the module comment).
const db = supabase as unknown as SupabaseClient;

export async function getPacketByRunId(runId: string): Promise<Packet | null> {
  const { data, error } = await db.from("packets").select("*").eq("run_id", runId).maybeSingle();
  if (error) throw new Error(error.message);
  return (data as Packet) ?? null;
}

export async function listPacketQuestions(packetId: string): Promise<PacketQuestion[]> {
  const { data, error } = await db
    .from("packet_questions")
    .select("*")
    .eq("packet_id", packetId)
    .order("position", { ascending: true });
  if (error) throw new Error(error.message);
  return (data ?? []) as PacketQuestion[];
}

export async function updatePacketQuestion(
  id: string,
  patch: Partial<
    Pick<PacketQuestion, "prompt" | "guidance" | "response_space" | "locked" | "position">
  > & { edited?: boolean },
): Promise<void> {
  const { error } = await db
    .from("packet_questions")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function addPacketQuestion(input: {
  packetId: string;
  position: number;
  prompt: string;
  functionName: QuestionFunction;
  responseSpace: ResponseSpace;
}): Promise<void> {
  const { data: userData, error: userErr } = await supabase.auth.getUser();
  if (userErr || !userData.user) throw new Error("Not signed in");
  const { error } = await db.from("packet_questions").insert({
    packet_id: input.packetId,
    user_id: userData.user.id,
    position: input.position,
    function: input.functionName,
    claim_ref: "",
    prompt: input.prompt,
    guidance: null,
    response_space: input.responseSpace,
    source: "user",
    edited: false,
  });
  if (error) throw new Error(error.message);
}

export async function deletePacketQuestion(id: string): Promise<void> {
  const { error } = await db.from("packet_questions").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

/** Approve the packet for printing: generated → reviewed (owner-only). */
export async function approvePacket(packetId: string): Promise<void> {
  const { error } = await db.from("packets").update({ status: "reviewed" }).eq("id", packetId);
  if (error) throw new Error(error.message);
}
