// Reference implementations of the final-artifact design systems.
//
// The real DOCX/PPTX are produced by cloud agents following the prompts in
// supabase/functions/_shared/followup-final.ts (buildFinalDocxPrompt /
// buildFinalPptxPrompt). This repo cannot run those agents, so these
// generators implement the same mandatory design rules with the same
// libraries the prompts name (`docx`, `pptxgenjs`), from the safe fixture in
// tests/fixtures/office/sample-piece.ts. tests/office-artifacts.test.ts
// generates both samples into test-artifacts/office/ and asserts the
// prompts' structural requirements hold — so a prompt rule that cannot
// actually be satisfied, or a validator rule that rejects a well-formed
// artifact, fails here instead of in production.
//
// If a design rule changes in the prompts, change it here (and in the
// tests) in the same commit.

import {
  AlignmentType,
  Document,
  ExternalHyperlink,
  Footer,
  HeadingLevel,
  LineRuleType,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import Pptxgen from "pptxgenjs";
import { samplePiece, type SamplePiece } from "./fixtures/office/sample-piece";

// The shared accent (deep forest green) and neutrals from the prompts'
// design sections. Grayscale-safe: the accent is only ever a heading color
// or a thin rule, never an information carrier.
const ACCENT = "1F4D3A";
const CHARCOAL = "222222";
const MUTED = "666666";
const CREAM = "F7F4EC";
const SERIF = "Georgia";

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

const PT = 2; // docx run sizes are half-points
const ONE_INCH = 1440; // twips

function body(text: string): Paragraph {
  return new Paragraph({ text });
}

function h1(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1 });
}

function h2(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2 });
}

function sourceLink(label: string, url: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: "Source: ", color: MUTED }),
      new ExternalHyperlink({
        children: [new TextRun({ text: label, style: "Hyperlink" })],
        link: url,
      }),
    ],
  });
}

function bulletList(items: string[]): Paragraph[] {
  return items.map((text) => new Paragraph({ text, bullet: { level: 0 } }));
}

export async function generateSampleDocx(piece: SamplePiece = samplePiece): Promise<Uint8Array> {
  const costTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: ["Cost", "Visible?", "Typical scale"].map(
          (text) =>
            new TableCell({
              shading: { fill: "F0EFED" },
              children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
            }),
        ),
      }),
      ...[
        ["Incident archaeology", "After the fact", "Days per incident"],
        ["Duplicate rebuilds", "Rarely", "One rebuild per two years"],
        ["Trust erosion", "Never", "Compounds quarterly"],
      ].map(
        (cells) =>
          new TableRow({
            children: cells.map((text) => new TableCell({ children: [new Paragraph({ text })] })),
          }),
      ),
    ],
  });

  const doc = new Document({
    title: piece.title,
    creator: piece.studentName,
    subject: piece.researchQuestion,
    description: "Final research document generated by Hardcopy Draft.",
    styles: {
      default: {
        document: {
          run: { font: SERIF, size: 11 * PT, color: CHARCOAL },
          // ~1.3 line spacing and 8pt space after — spacing lives in the
          // style, never in blank paragraphs. lineRule must be explicit:
          // LibreOffice reads a bare w:line as an exact height, which
          // crushes multi-line headings.
          paragraph: { spacing: { line: 312, lineRule: LineRuleType.AUTO, after: 160 } },
        },
      },
      paragraphStyles: [
        {
          id: "Title",
          name: "Title",
          basedOn: "Normal",
          run: { font: SERIF, size: 28 * PT, bold: true, color: CHARCOAL },
          paragraph: { spacing: { before: 2880, after: 240 } },
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: SERIF, size: 16 * PT, bold: true, color: ACCENT },
          paragraph: { spacing: { before: 320, after: 120 }, keepNext: true },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: SERIF, size: 13 * PT, bold: true, color: CHARCOAL },
          paragraph: { spacing: { before: 240, after: 80 }, keepNext: true },
        },
      ],
    },
    sections: [
      // Title page: its own section so the page-number footer starts on the
      // first content page.
      {
        properties: {
          page: { margin: { top: ONE_INCH, right: ONE_INCH, bottom: ONE_INCH, left: ONE_INCH } },
        },
        children: [
          new Paragraph({ text: piece.title, style: "Title", alignment: AlignmentType.CENTER }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: piece.researchQuestion, italics: true, color: MUTED })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 480 },
            children: [new TextRun({ text: piece.studentName })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: piece.date, color: MUTED })],
          }),
        ],
      },
      {
        properties: {
          page: { margin: { top: ONE_INCH, right: ONE_INCH, bottom: ONE_INCH, left: ONE_INCH } },
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Page ", size: 9 * PT, color: MUTED }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 9 * PT, color: MUTED }),
                ],
              }),
            ],
          }),
        },
        children: [
          h1("Executive summary"),
          body(piece.executiveSummary),

          h1("Findings"),
          ...piece.findings.flatMap((f) => [
            h2(f.headline),
            body(f.body),
            sourceLink(f.source.label, f.source.url),
          ]),
          h2("What the fade actually costs"),
          costTable,
          h2(`${piece.followupFindings.headline} (second-pass research)`),
          body(piece.followupFindings.body),
          sourceLink(piece.followupFindings.source.label, piece.followupFindings.source.url),

          h1("In the student's words"),
          ...piece.verifiedResponses.flatMap((r) => [
            new Paragraph({
              children: [new TextRun({ text: r.prompt, italics: true, color: MUTED })],
            }),
            new Paragraph({
              children: [new TextRun({ text: `\u201C${r.response}\u201D` })],
            }),
          ]),

          h1("Uncertainties and next steps"),
          ...bulletList(piece.uncertainties),
          body("Next steps:"),
          ...bulletList(piece.nextSteps),

          h1("Sources"),
          ...piece.sources.map(
            (s) =>
              new Paragraph({
                children: [
                  new ExternalHyperlink({
                    children: [new TextRun({ text: `${s.label} — ${s.url}`, style: "Hyperlink" })],
                    link: s.url,
                  }),
                ],
              }),
          ),
        ],
      },
    ],
  });

  return new Uint8Array(await Packer.toBuffer(doc));
}

// ---------------------------------------------------------------------------
// PPTX
// ---------------------------------------------------------------------------

// 16:9 geometry (inches). Content stays inside these margins; the source
// line and slide number sit in the footer band but never touch the edge.
const SLIDE_W = 13.33;
const CONTENT_X = 0.6;
const CONTENT_W = SLIDE_W - 2 * CONTENT_X;

type Slide = ReturnType<InstanceType<typeof Pptxgen>["addSlide"]>;

function addTitle(slide: Slide, text: string) {
  slide.addText(text, {
    x: CONTENT_X,
    y: 0.45,
    w: CONTENT_W,
    h: 0.9,
    fontSize: 29,
    fontFace: SERIF,
    color: ACCENT,
    bold: true,
    valign: "middle",
  });
}

function addBullets(slide: Slide, items: string[]) {
  slide.addText(
    items.map((text) => ({ text, options: { bullet: { indent: 12 }, breakLine: true } })),
    {
      x: CONTENT_X,
      y: 1.9,
      w: CONTENT_W,
      h: 4.2,
      fontSize: 20,
      fontFace: SERIF,
      color: CHARCOAL,
      valign: "top",
      paraSpaceAfter: 12,
    },
  );
}

function addSourceLine(slide: Slide, label: string, url: string) {
  slide.addText(`Source: ${label} — ${url}`, {
    x: CONTENT_X,
    y: 6.85,
    w: CONTENT_W - 0.9, // clear the slide-number box bottom-right
    h: 0.35,
    fontSize: 11,
    fontFace: SERIF,
    color: MUTED,
    valign: "middle",
  });
}

export async function generateSamplePptx(piece: SamplePiece = samplePiece): Promise<Uint8Array> {
  const pptx = new Pptxgen();
  pptx.layout = "LAYOUT_WIDE"; // 13.33 × 7.5in (16:9)
  pptx.title = piece.title;
  pptx.author = piece.studentName;
  pptx.subject = piece.researchQuestion;

  // ONE look, defined once. The accent appears only as the rule under the
  // title; the slide number sits bottom-right on every slide that uses this
  // master (the title slide uses TITLE, which has none).
  pptx.defineSlideMaster({
    title: "CONTENT",
    background: { color: CREAM },
    objects: [{ rect: { x: CONTENT_X, y: 1.45, w: CONTENT_W, h: 0.03, fill: { color: ACCENT } } }],
    slideNumber: {
      x: 12.55,
      y: 7.02,
      w: 0.55,
      h: 0.35,
      fontSize: 11,
      fontFace: SERIF,
      color: MUTED,
    },
  });
  pptx.defineSlideMaster({ title: "TITLE", background: { color: CREAM } });

  // 1. Title
  const title = pptx.addSlide({ masterName: "TITLE" });
  title.addText(piece.title, {
    x: CONTENT_X,
    y: 2.5,
    w: CONTENT_W,
    h: 1.4,
    fontSize: 40,
    fontFace: SERIF,
    color: CHARCOAL,
    bold: true,
    align: "center",
    valign: "middle",
  });
  title.addText(`${piece.studentName} · ${piece.date}`, {
    x: CONTENT_X,
    y: 4.1,
    w: CONTENT_W,
    h: 0.5,
    fontSize: 18,
    fontFace: SERIF,
    color: MUTED,
    align: "center",
  });

  // 2. The research question and why it matters.
  const question = pptx.addSlide({ masterName: "CONTENT" });
  addTitle(question, piece.researchQuestion);
  addBullets(question, piece.whyItMatters);
  question.addNotes(
    "Frame the inquiry: this started as a technical-debt question and became an " +
      "ownership question. Walk through why each of these stakes is personal to the team.",
  );

  // 3–5. Major findings, one per slide.
  for (const f of piece.findings) {
    const slide = pptx.addSlide({ masterName: "CONTENT" });
    addTitle(slide, f.headline);
    addBullets(slide, f.bullets);
    addSourceLine(slide, f.source.label, f.source.url);
    slide.addNotes(f.body);
  }

  // 6. Verified student responses — headline paraphrase on the slide,
  // verbatim quotes only in the notes.
  const voices = pptx.addSlide({ masterName: "CONTENT" });
  addTitle(voices, "What I actually changed my mind about");
  addBullets(
    voices,
    piece.verifiedResponses.map((r) => r.prompt),
  );
  voices.addNotes(piece.verifiedResponses.map((r) => `Verbatim: "${r.response}"`).join("\n\n"));

  // 7. Uncertainties.
  const unknowns = pptx.addSlide({ masterName: "CONTENT" });
  addTitle(unknowns, "What the evidence does not establish");
  addBullets(unknowns, piece.uncertainties);
  unknowns.addNotes(
    "Be explicit that the postmortem data oversamples failures — the honest version " +
      "of this claim is correlation, not causation.",
  );

  // 8. Follow-up findings (second pass).
  const followup = pptx.addSlide({ masterName: "CONTENT" });
  addTitle(followup, piece.followupFindings.headline);
  addBullets(followup, [
    "Two additional case studies, same arc",
    "Ownership diluted within two quarters of the reorg",
    "First silent failure within a year — causation still open",
  ]);
  addSourceLine(followup, piece.followupFindings.source.label, piece.followupFindings.source.url);
  followup.addNotes(piece.followupFindings.body);

  // 9. Sources.
  const sources = pptx.addSlide({ masterName: "CONTENT" });
  addTitle(sources, "Sources");
  addBullets(
    sources,
    piece.sources.map((s) => `${s.label} — ${s.url}`),
  );
  sources.addNotes("All sources are fictional fixture data for the sample artifact.");

  const out = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return new Uint8Array(out);
}
