/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as InterludeRouteImport } from './routes/interlude'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as ApiPublicGenerateImageRouteImport } from './routes/api/public/generate-image'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated/runs.$runId'
import { Route as AuthenticatedReviewReturnIdRouteImport } from './routes/_authenticated/review.$returnId'
import { Route as AuthenticatedReturnPacketIdRouteImport } from './routes/_authenticated/return.$packetId'
import { Route as AuthenticatedProjectPieceIdRouteImport } from './routes/_authenticated/project.$pieceId'
import { Route as AuthenticatedPrintRunIdRouteImport } from './routes/_authenticated/print.$runId'
import { Route as AuthenticatedPacketRunIdRouteImport } from './routes/_authenticated/packet.$runId'
import { Route as AuthenticatedFollowupPacketIdRouteImport } from './routes/_authenticated/followup.$packetId'

const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const InterludeRoute = InterludeRouteImport.update({
  id: '/interlude',
  path: '/interlude',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGenerateImageRoute = ApiPublicGenerateImageRouteImport.update({
  id: '/api/public/generate-image',
  path: '/api/public/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewReturnIdRoute =
  AuthenticatedReviewReturnIdRouteImport.update({
    id: '/review/$returnId',
    path: '/review/$returnId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnPacketIdRoute =
  AuthenticatedReturnPacketIdRouteImport.update({
    id: '/return/$packetId',
    path: '/return/$packetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectPieceIdRoute =
  AuthenticatedProjectPieceIdRouteImport.update({
    id: '/project/$pieceId',
    path: '/project/$pieceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintRunIdRoute = AuthenticatedPrintRunIdRouteImport.update({
  id: '/print/$runId',
  path: '/print/$runId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacketRunIdRoute =
  AuthenticatedPacketRunIdRouteImport.update({
    id: '/packet/$runId',
    path: '/packet/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowupPacketIdRoute =
  AuthenticatedFollowupPacketIdRouteImport.update({
    id: '/followup/$packetId',
    path: '/followup/$packetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/canon': typeof CanonRoute
  '/interlude': typeof InterludeRoute
  '/proof': typeof ProofRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/followup/$packetId': typeof AuthenticatedFollowupPacketIdRoute
  '/packet/$runId': typeof AuthenticatedPacketRunIdRoute
  '/print/$runId': typeof AuthenticatedPrintRunIdRoute
  '/project/$pieceId': typeof AuthenticatedProjectPieceIdRoute
  '/return/$packetId': typeof AuthenticatedReturnPacketIdRoute
  '/review/$returnId': typeof AuthenticatedReviewReturnIdRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/generate-image': typeof ApiPublicGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/canon': typeof CanonRoute
  '/interlude': typeof InterludeRoute
  '/proof': typeof ProofRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/followup/$packetId': typeof AuthenticatedFollowupPacketIdRoute
  '/packet/$runId': typeof AuthenticatedPacketRunIdRoute
  '/print/$runId': typeof AuthenticatedPrintRunIdRoute
  '/project/$pieceId': typeof AuthenticatedProjectPieceIdRoute
  '/return/$packetId': typeof AuthenticatedReturnPacketIdRoute
  '/review/$returnId': typeof AuthenticatedReviewReturnIdRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/generate-image': typeof ApiPublicGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/canon': typeof CanonRoute
  '/interlude': typeof InterludeRoute
  '/proof': typeof ProofRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/followup/$packetId': typeof AuthenticatedFollowupPacketIdRoute
  '/_authenticated/packet/$runId': typeof AuthenticatedPacketRunIdRoute
  '/_authenticated/print/$runId': typeof AuthenticatedPrintRunIdRoute
  '/_authenticated/project/$pieceId': typeof AuthenticatedProjectPieceIdRoute
  '/_authenticated/return/$packetId': typeof AuthenticatedReturnPacketIdRoute
  '/_authenticated/review/$returnId': typeof AuthenticatedReviewReturnIdRoute
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/public/generate-image': typeof ApiPublicGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/canon'
    | '/interlude'
    | '/proof'
    | '/billing'
    | '/dashboard'
    | '/new'
    | '/profile'
    | '/sessions'
    | '/api/transcribe'
    | '/followup/$packetId'
    | '/packet/$runId'
    | '/print/$runId'
    | '/project/$pieceId'
    | '/return/$packetId'
    | '/review/$returnId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/api/public/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/canon'
    | '/interlude'
    | '/proof'
    | '/billing'
    | '/dashboard'
    | '/new'
    | '/profile'
    | '/sessions'
    | '/api/transcribe'
    | '/followup/$packetId'
    | '/packet/$runId'
    | '/print/$runId'
    | '/project/$pieceId'
    | '/return/$packetId'
    | '/review/$returnId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/api/public/generate-image'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/canon'
    | '/interlude'
    | '/proof'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/profile'
    | '/_authenticated/sessions'
    | '/api/transcribe'
    | '/_authenticated/followup/$packetId'
    | '/_authenticated/packet/$runId'
    | '/_authenticated/print/$runId'
    | '/_authenticated/project/$pieceId'
    | '/_authenticated/return/$packetId'
    | '/_authenticated/review/$returnId'
    | '/_authenticated/runs/$runId'
    | '/_authenticated/sessions/$sessionId'
    | '/api/public/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CanonRoute: typeof CanonRoute
  InterludeRoute: typeof InterludeRoute
  ProofRoute: typeof ProofRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPublicGenerateImageRoute: typeof ApiPublicGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interlude': {
      id: '/interlude'
      path: '/interlude'
      fullPath: '/interlude'
      preLoaderRoute: typeof InterludeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/generate-image': {
      id: '/api/public/generate-image'
      path: '/api/public/generate-image'
      fullPath: '/api/public/generate-image'
      preLoaderRoute: typeof ApiPublicGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$returnId': {
      id: '/_authenticated/review/$returnId'
      path: '/review/$returnId'
      fullPath: '/review/$returnId'
      preLoaderRoute: typeof AuthenticatedReviewReturnIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/return/$packetId': {
      id: '/_authenticated/return/$packetId'
      path: '/return/$packetId'
      fullPath: '/return/$packetId'
      preLoaderRoute: typeof AuthenticatedReturnPacketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project/$pieceId': {
      id: '/_authenticated/project/$pieceId'
      path: '/project/$pieceId'
      fullPath: '/project/$pieceId'
      preLoaderRoute: typeof AuthenticatedProjectPieceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/$runId': {
      id: '/_authenticated/print/$runId'
      path: '/print/$runId'
      fullPath: '/print/$runId'
      preLoaderRoute: typeof AuthenticatedPrintRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packet/$runId': {
      id: '/_authenticated/packet/$runId'
      path: '/packet/$runId'
      fullPath: '/packet/$runId'
      preLoaderRoute: typeof AuthenticatedPacketRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followup/$packetId': {
      id: '/_authenticated/followup/$packetId'
      path: '/followup/$packetId'
      fullPath: '/followup/$packetId'
      preLoaderRoute: typeof AuthenticatedFollowupPacketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedFollowupPacketIdRoute: typeof AuthenticatedFollowupPacketIdRoute
  AuthenticatedPacketRunIdRoute: typeof AuthenticatedPacketRunIdRoute
  AuthenticatedPrintRunIdRoute: typeof AuthenticatedPrintRunIdRoute
  AuthenticatedProjectPieceIdRoute: typeof AuthenticatedProjectPieceIdRoute
  AuthenticatedReturnPacketIdRoute: typeof AuthenticatedReturnPacketIdRoute
  AuthenticatedReviewReturnIdRoute: typeof AuthenticatedReviewReturnIdRoute
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedFollowupPacketIdRoute: AuthenticatedFollowupPacketIdRoute,
  AuthenticatedPacketRunIdRoute: AuthenticatedPacketRunIdRoute,
  AuthenticatedPrintRunIdRoute: AuthenticatedPrintRunIdRoute,
  AuthenticatedProjectPieceIdRoute: AuthenticatedProjectPieceIdRoute,
  AuthenticatedReturnPacketIdRoute: AuthenticatedReturnPacketIdRoute,
  AuthenticatedReviewReturnIdRoute: AuthenticatedReviewReturnIdRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CanonRoute: CanonRoute,
  InterludeRoute: InterludeRoute,
  ProofRoute: ProofRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPublicGenerateImageRoute: ApiPublicGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
